import json
import logging
import requests
from datetime import datetime

from config import (
    JIRA_URL,
    JIRA_EMAIL,
    JIRA_API_TOKEN,
    PROJECT_KEY,
    ZEPHYR_ENABLED,
    ZEPHYR_API_TOKEN,
)

logger = logging.getLogger(__name__)

# Zephyr Scale REST API base (Jira Cloud)
_ZEPHYR_BASE = "https://api.zephyrscale.smartbear.com/v2"


def _zephyr_headers():
    return {
        "Authorization": f"Bearer {ZEPHYR_API_TOKEN}",
        "Content-Type": "application/json",
    }


def _jira_auth():
    return (JIRA_EMAIL, JIRA_API_TOKEN)


# ── Zephyr Scale helpers ─────────────────────────────────────────────────────

def _get_project_id(project_key):
    """Resolve a Jira project key to a Zephyr project ID."""
    try:
        resp = requests.get(
            f"{_ZEPHYR_BASE}/projects",
            headers=_zephyr_headers(),
            timeout=15
        )
        resp.raise_for_status()
        for proj in resp.json().get("values", []):
            if proj.get("key") == project_key:
                return proj.get("id")
    except Exception as e:
        logger.error("Could not fetch Zephyr projects: %s", e)
    return None


def _create_test_case(issue_key, summary, test_cases_text, project_id):
    """Create a Zephyr Scale test case linked to a Jira issue."""
    steps = []
    for i, line in enumerate(test_cases_text.strip().split("\n"), 1):
        line = line.strip()
        if line:
            steps.append({
                "description": line,
                "testData": "",
                "expectedResult": "As described"
            })

    payload = {
        "projectKey": PROJECT_KEY,
        "name": f"[AI] {summary[:100]}",
        "objective": f"Auto-generated test case for Jira issue {issue_key}",
        "labels": ["AI-Generated", "Dynamics365"],
        "steps": steps,
    }

    try:
        resp = requests.post(
            f"{_ZEPHYR_BASE}/testcases",
            headers=_zephyr_headers(),
            json=payload,
            timeout=15
        )
        resp.raise_for_status()
        tc = resp.json()
        tc_key = tc.get("key")
        logger.info("Created Zephyr test case %s for %s", tc_key, issue_key)
        return tc_key
    except Exception as e:
        logger.error("Failed to create Zephyr test case for %s: %s", issue_key, e)
        return None


def _create_test_cycle(project_id, run_label):
    """Create a Zephyr test cycle for this automation run."""
    payload = {
        "projectKey": PROJECT_KEY,
        "name": f"AI Automation Run — {run_label}",
        "description": "Automatically generated by the Dynamics 365 AI Test Agent",
        "statusName": "In Progress",
    }
    try:
        resp = requests.post(
            f"{_ZEPHYR_BASE}/testcycles",
            headers=_zephyr_headers(),
            json=payload,
            timeout=15
        )
        resp.raise_for_status()
        cycle = resp.json()
        cycle_key = cycle.get("key")
        logger.info("Created Zephyr test cycle: %s", cycle_key)
        return cycle_key
    except Exception as e:
        logger.error("Failed to create Zephyr test cycle: %s", e)
        return None


def _post_execution(tc_key, cycle_key, status, comment):
    """Post a test execution result to Zephyr Scale."""
    # Zephyr statuses: Pass, Fail, In Progress, Not Executed, Blocked
    zephyr_status = "Pass" if str(status).startswith("PASS") else "Fail"

    payload = {
        "projectKey": PROJECT_KEY,
        "testCaseKey": tc_key,
        "testCycleKey": cycle_key,
        "statusName": zephyr_status,
        "comment": comment,
        "executionTime": 0,
    }
    try:
        resp = requests.post(
            f"{_ZEPHYR_BASE}/testexecutions",
            headers=_zephyr_headers(),
            json=payload,
            timeout=15
        )
        resp.raise_for_status()
        logger.info("Posted Zephyr execution: %s → %s", tc_key, zephyr_status)
        return True
    except Exception as e:
        logger.error("Failed to post Zephyr execution for %s: %s", tc_key, e)
        return False


# ── Jira comment fallback ────────────────────────────────────────────────────

def _post_jira_comment(issue_key, test_cases, ai_plan, test_status, screenshot_path):
    """Post results as a Jira comment (fallback when Zephyr is not available)."""
    comment = (
        f"*[AI Test Agent] Test Execution Result*\n\n"
        f"*Status:* {test_status}\n\n"
        f"*AI Generated Test Cases:*\n\n{test_cases}\n\n"
        f"*AI Selected Workflow:*\n"
        f"{{code:json}}\n{json.dumps(ai_plan, indent=2)}\n{{code}}\n\n"
        f"*Screenshot Evidence:* {screenshot_path}"
    )
    try:
        url = f"{JIRA_URL}/rest/api/3/issue/{issue_key}/comment"
        resp = requests.post(
            url,
            auth=_jira_auth(),
            json={"body": {"type": "doc", "version": 1,
                           "content": [{"type": "paragraph",
                                        "content": [{"type": "text", "text": comment}]}]}},
            timeout=15
        )
        # Fallback to v2 API format if v3 fails
        if resp.status_code not in (200, 201):
            url_v2 = f"{JIRA_URL}/rest/api/2/issue/{issue_key}/comment"
            resp = requests.post(
                url_v2,
                auth=_jira_auth(),
                json={"body": comment},
                timeout=15
            )
        resp.raise_for_status()
        logger.info("Posted Jira comment fallback for %s", issue_key)
        return True
    except Exception as e:
        logger.error("Failed to post Jira comment for %s: %s", issue_key, e)
        return False


# ── Public interface ─────────────────────────────────────────────────────────

_cycle_key_cache = {}  # one cycle per run, shared across issues


def post_test_result(issue_key, summary, test_cases, ai_plan, test_status, screenshot_path):
    """Post a test result to Zephyr Scale if enabled, otherwise fall back to a Jira comment.

    Args:
        issue_key:       Jira issue key, e.g. "KAN-1"
        summary:         User story summary text
        test_cases:      AI-generated test case text
        ai_plan:         AI workflow decision dict
        test_status:     Status string, e.g. "PASS" or "FAIL - ..."
        screenshot_path: Path to the evidence screenshot

    Returns:
        True if posted successfully (either Zephyr or Jira), False otherwise.
    """
    comment = (
        f"Automated by AI Test Agent.\n"
        f"Status: {test_status}\n"
        f"Screenshot: {screenshot_path}\n\n"
        f"Test Cases:\n{test_cases}"
    )

    if ZEPHYR_ENABLED and ZEPHYR_API_TOKEN:
        logger.info("[%s] Posting to Zephyr Scale...", issue_key)

        # Get/create the test cycle once per run
        run_label = datetime.now().strftime("%Y-%m-%d %H:%M")
        cache_key = "cycle"

        if cache_key not in _cycle_key_cache:
            project_id = _get_project_id(PROJECT_KEY)
            cycle_key = _create_test_cycle(project_id, run_label)
            _cycle_key_cache[cache_key] = cycle_key
        else:
            cycle_key = _cycle_key_cache[cache_key]

        if cycle_key:
            tc_key = _create_test_case(issue_key, summary, test_cases, None)
            if tc_key:
                return _post_execution(tc_key, cycle_key, test_status, comment)

        logger.warning("[%s] Zephyr posting failed, falling back to Jira comment", issue_key)

    # Fallback — plain Jira comment
    logger.info("[%s] Posting result as Jira comment", issue_key)
    return _post_jira_comment(issue_key, test_cases, ai_plan, test_status, screenshot_path)


def reset_cycle_cache():
    """Call this at the start of each run to force a fresh test cycle."""
    _cycle_key_cache.clear()
